//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medidor
    {
        public int Id { get; set; }
        public Nullable<int> LecturaInicial { get; set; }
        public Nullable<int> UltimaLectura { get; set; }
        public string Tipo { get; set; }
    }
}
